language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script: 
  - composer install
  - php vendor/bin/phpcs --config-set default_standard PSR2
script: 
  - php vendor/bin/phpmd src
  - php -d date.timezone=Europe/Paris vendor/bin/phpmd src text codesize,unusedcode,naming,design,controversial